[2023-05-08T04:25:25.902+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadArtistDim manual__2023-05-08T04:23:57.561687+00:00 [queued]>
[2023-05-08T04:25:25.907+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadArtistDim manual__2023-05-08T04:23:57.561687+00:00 [queued]>
[2023-05-08T04:25:25.908+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-08T04:25:25.916+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.LoadArtistDim> on 2023-05-08 04:23:57.561687+00:00
[2023-05-08T04:25:25.921+0000] {standard_task_runner.py:57} INFO - Started process 3964 to run task
[2023-05-08T04:25:25.924+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadArtistDim', 'manual__2023-05-08T04:23:57.561687+00:00', '--job-id', '2152', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpkq9xflnq']
[2023-05-08T04:25:25.925+0000] {standard_task_runner.py:85} INFO - Job 2152: Subtask LoadData.LoadArtistDim
[2023-05-08T04:25:25.957+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadArtistDim manual__2023-05-08T04:23:57.561687+00:00 [running]> on host a40687a10d43
[2023-05-08T04:25:26.007+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadArtistDim' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T04:23:57.561687+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T04:23:57.561687+00:00'
[2023-05-08T04:25:26.009+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_database() missing 1 required positional argument: 'primary_key'
[2023-05-08T04:25:26.016+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadArtistDim, execution_date=20230508T042357, start_date=20230508T042525, end_date=20230508T042526
[2023-05-08T04:25:26.022+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2152 for task LoadData.LoadArtistDim (upload_to_database() missing 1 required positional argument: 'primary_key'; 3964)
[2023-05-08T04:25:26.057+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T04:25:26.073+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
