[2023-05-08T16:13:29.487+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongFact manual__2023-05-08T16:09:58.195696+00:00 [queued]>
[2023-05-08T16:13:29.492+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongFact manual__2023-05-08T16:09:58.195696+00:00 [queued]>
[2023-05-08T16:13:29.493+0000] {taskinstance.py:1331} INFO - Starting attempt 5 of 6
[2023-05-08T16:13:29.500+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.LoadSongFact> on 2023-05-08 16:09:58.195696+00:00
[2023-05-08T16:13:29.505+0000] {standard_task_runner.py:57} INFO - Started process 993 to run task
[2023-05-08T16:13:29.509+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadSongFact', 'manual__2023-05-08T16:09:58.195696+00:00', '--job-id', '2490', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpelwfcauz']
[2023-05-08T16:13:29.509+0000] {standard_task_runner.py:85} INFO - Job 2490: Subtask LoadData.LoadSongFact
[2023-05-08T16:13:29.546+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadSongFact manual__2023-05-08T16:09:58.195696+00:00 [running]> on host 7b4753e133cb
[2023-05-08T16:13:29.602+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadSongFact' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T16:09:58.195696+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T16:09:58.195696+00:00'
[2023-05-08T16:13:29.604+0000] {logging_mixin.py:149} INFO - 2023-05/song_fact.csv
[2023-05-08T16:13:29.612+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-05-08T16:13:29.613+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-05-08T16:13:29.879+0000] {logging_mixin.py:149} INFO -                   song_id  popularity        date
0  7evQqGTWfKz8hIHzLVzneT          45  2023-05-08
1  3PDNGdhCtiQemL14eKhCup          49  2023-05-08
2  1bLEa8W1VVMFBIwp9hKYTL          44  2023-05-08
3  7H74AdiJYM7hh4SYGrq9xe          53  2023-05-08
4  2SWK4LJWLyev4yVYIVhjEV          33  2023-05-08
[2023-05-08T16:13:29.880+0000] {logging_mixin.py:149} INFO - INSERT INTO song_fact (song_id,popularity,date) VALUES (%s,%s,%s) ON CONFLICT (song_id,date) DO UPDATE SET song_id=EXCLUDED.song_id,popularity=EXCLUDED.popularity,date=EXCLUDED.date
[2023-05-08T16:13:29.888+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-05-08T16:13:29.897+0000] {sql.py:375} INFO - Running statement: INSERT INTO song_fact (song_id,popularity,date) VALUES (%s,%s,%s) ON CONFLICT (song_id,date) DO UPDATE SET song_id=EXCLUDED.song_id,popularity=EXCLUDED.popularity,date=EXCLUDED.date, parameters: ('7evQqGTWfKz8hIHzLVzneT', 45, '2023-05-08')
[2023-05-08T16:13:29.899+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 41, in upload_to_database
    postgres_hook.run(insert_sql, parameters=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 378, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2023-05-08T16:13:29.908+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadSongFact, execution_date=20230508T160958, start_date=20230508T161329, end_date=20230508T161329
[2023-05-08T16:13:29.914+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2490 for task LoadData.LoadSongFact (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 993)
[2023-05-08T16:13:29.962+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T16:13:29.980+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
